In [1]:
# Modules
import requests
import re
import pandas as pd
from bs4 import BeautifulSoup

In [2]:
spaceWeather = requests.get('https://www.spaceweatherlive.com/en/solar-activity/top-50-solar-flares')
sapceWeather_text = spaceWeather.text
spaceWeather_page = BeautifulSoup(sapceWeather_text)
spaceWeather_page.prettify()[:1000]

'<!DOCTYPE html>\n<html lang="en">\n <head>\n  <title>\n   Top 50 solar flares | Solar activity | SpaceWeatherLive.com\n  </title>\n  <meta charset="utf-8"/>\n  <meta content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1" name="robots"/>\n  <meta content="On this page you will find an overview of the strongest solar flares since June 1996 together with links to more information in our archive and a v..." name="description"/>\n  <meta content="SpaceWeatherLive, Live, Aurora, Auroral activity, Aurora Australis, Aurora Borealis, northern lights, Solar wind, Kp-index, Space Weather, Space Weather Updates, Aurora forecast, Space Weather Alerts, Solar activity, Solar flares, Sunspots, Aurora alert, Auroral activity, The Sun, SDO, STEREO, EPAM, DSCOVR" name="keywords"/>\n  <!-- Facebook meta -->\n  <meta content="https://spaceweatherlive.com/en/solar-activity/top-50-solar-flares" property="og:url"/>\n  <meta content="article" property="og:type"/>\n  <meta content="Top 50 sol'

In [3]:
table = spaceWeather_page.find_all('table', class_='table table-striped table-responsive-md')
len(table)

1

In [4]:
table[0]

<table class="table table-striped table-responsive-md"><thead><tr><th></th><th></th><th></th><th>Region</th><th>Start</th><th>Maximum</th><th>End</th><th></th></tr></thead><tbody><tr><td>1</td><td><span class="flare_small Xclass">X28+</span></td><td>2003/11/04</td><td><span class="badge badge-region_mag BGD"><a href="/en/solar-activity/region/10486">0486</a></span></td><td>19:29</td><td>19:53</td><td>20:06</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/2003/Flares/200311041953X28.0.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/2003/11/04/xray">View archive</a></div></td></tr><tr><td>2</td><td><span class="flare_small Xclass">X20+</span></td><td>2001/04/02</td><td><span class="badge badge-region_mag BGD"><a href="/en/solar-activity/region/9393">9393</a></span></td><td>21:32</td><td>21:51</td><td>22:03</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/2001/Flares/200104022151X20.0.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/2001/04/02/xray">View archive</a></div></td></tr><tr><td>3</td><td><span class="flare_small Xclass">X17.2+</span></td><td>2003/10/28</td><td><span class="badge badge-region_mag BGD"><a href="/en/solar-activity/region/10486">0486</a></span></td><td>09:51</td><td>11:10</td><td>11:24</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/2003/Flares/200310281110X17.2.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/2003/10/28/xray">View archive</a></div></td></tr><tr><td>4</td><td><span class="flare_small Xclass">X17+</span></td><td>2005/09/07</td><td><span class="badge badge-region_mag"><a href="/en/solar-activity/region/10808">0808</a></span></td><td>17:17</td><td>17:40</td><td>18:03</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/2005/Flares/200509071740X17.0.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/2005/09/07/xray">View archive</a></div></td></tr><tr><td>5</td><td><span class="flare_small Xclass">X14.4</span></td><td>2001/04/15</td><td><span class="badge badge-region_mag BG"><a href="/en/solar-activity/region/9415">9415</a></span></td><td>13:19</td><td>13:50</td><td>13:55</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/2001/Flares/200104151350X14.4.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/2001/04/15/xray">View archive</a></div></td></tr><tr><td>6</td><td><span class="flare_small Xclass">X10</span></td><td>2003/10/29</td><td><span class="badge badge-region_mag BGD"><a href="/en/solar-activity/region/10486">0486</a></span></td><td>20:37</td><td>20:49</td><td>21:01</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/2003/Flares/200310292049X10.0.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/2003/10/29/xray">View archive</a></div></td></tr><tr><td>7</td><td><span class="flare_small Xclass">X9.4</span></td><td>1997/11/06</td><td><span class="badge badge-region_mag BGD"><a href="/en/solar-activity/region/8100">8100</a></span></td><td>11:49</td><td>11:55</td><td>12:01</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/1997/Flares/199711061155X9.4.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/1997/11/06/xray">View archive</a></div></td></tr><tr><td>8</td><td><span class="flare_small Xclass">X9.3</span></td><td>2017/09/06</td><td><span class="badge badge-region_mag BGD"><a href="/en/solar-activity/region/12673">2673</a></span></td><td>11:53</td><td>12:02</td><td>12:10</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/2017/Flares/201709061202X9.3.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/2017/09/06/xray">View archive</a></div></td></tr><tr><td>9</td><td><span class="flare_small Xclass">X9</span></td><td>2006/12/05</td><td><span class="badge badge-region_mag"><a href="/en/solar-activity/region/10930">0930</a></span></td><td>10:18</td><td>10:35</td><td>10:45</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/2006/Flares/200612051035X9.0.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/2006/12/05/xray">View archive</a></div></td></tr><tr><td>10</td><td><span class="flare_small Xclass">X8.3</span></td><td>2003/11/02</td><td><span class="badge badge-region_mag BGD"><a href="/en/solar-activity/region/10486">0486</a></span></td><td>17:03</td><td>17:25</td><td>17:39</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/2003/Flares/200311021725X8.3.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/2003/11/02/xray">View archive</a></div></td></tr><tr><td>11</td><td><span class="flare_small Xclass">X8.2</span></td><td>2017/09/10</td><td><span class="badge badge-region_mag BGD"><a href="/en/solar-activity/region/12673">2673</a></span></td><td>15:35</td><td>16:06</td><td>16:31</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/2017/Flares/201709101606X8.2.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/2017/09/10/xray">View archive</a></div></td></tr><tr><td>12</td><td><span class="flare_small Xclass">X7.1</span></td><td>2005/01/20</td><td><span class="badge badge-region_mag BD"><a href="/en/solar-activity/region/10720">0720</a></span></td><td>06:36</td><td>07:01</td><td>07:26</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/2005/Flares/200501200701X7.1.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/2005/01/20/xray">View archive</a></div></td></tr><tr><td>13</td><td><span class="flare_small Xclass">X6.9</span></td><td>2011/08/09</td><td><span class="badge badge-region_mag BGD"><a href="/en/solar-activity/region/11263">1263</a></span></td><td>07:48</td><td>08:05</td><td>08:08</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/2011/Flares/201108090805X6.9.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/2011/08/09/xray">View archive</a></div></td></tr><tr><td>14</td><td><span class="flare_small Xclass">X6.5</span></td><td>2006/12/06</td><td><span class="badge badge-region_mag B"><a href="/en/solar-activity/region/10930">0930</a></span></td><td>18:29</td><td>18:47</td><td>19:00</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/2006/Flares/200612061847X6.5.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/2006/12/06/xray">View archive</a></div></td></tr><tr><td>15</td><td><span class="flare_small Xclass">X6.2</span></td><td>2005/09/09</td><td><span class="badge badge-region_mag BG"><a href="/en/solar-activity/region/10808">0808</a></span></td><td>19:13</td><td>20:04</td><td>20:36</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/2005/Flares/200509092004X6.2.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/2005/09/09/xray">View archive</a></div></td></tr><tr><td>16</td><td><span class="flare_small Xclass">X6.2</span></td><td>2001/12/13</td><td><span class="badge badge-region_mag BGD"><a href="/en/solar-activity/region/9733">9733</a></span></td><td>14:20</td><td>14:30</td><td>14:35</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/2001/Flares/200112131430X6.2.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/2001/12/13/xray">View archive</a></div></td></tr><tr><td>17</td><td><span class="flare_small Xclass">X5.7</span></td><td>2000/07/14</td><td><span class="badge badge-region_mag BGD"><a href="/en/solar-activity/region/9077">9077</a></span></td><td>10:03</td><td>10:24</td><td>10:43</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/2000/Flares/200007141024X5.7.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/2000/07/14/xray">View archive</a></div></td></tr><tr><td>18</td><td><span class="flare_small Xclass">X5.6</span></td><td>2001/04/06</td><td><span class="badge badge-region_mag BG"><a href="/en/solar-activity/region/9415">9415</a></span></td><td>19:10</td><td>19:21</td><td>19:31</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/2001/Flares/200104061921X5.6.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/2001/04/06/xray">View archive</a></div></td></tr><tr><td>19</td><td><span class="flare_small Xclass">X5.4</span></td><td>2012/03/07</td><td><span class="badge badge-region_mag BGD"><a href="/en/solar-activity/region/11429">1429</a></span></td><td>00:02</td><td>00:24</td><td>00:40</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/2012/Flares/201203070024X5.4.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/2012/03/07/xray">View archive</a></div></td></tr><tr><td>20</td><td><span class="flare_small Xclass">X5.4</span></td><td>2005/09/08</td><td><span class="badge badge-region_mag A"><a href="/en/solar-activity/region/10808">0808</a></span></td><td>20:52</td><td>21:06</td><td>21:17</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/2005/Flares/200509082106X5.4.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/2005/09/08/xray">View archive</a></div></td></tr><tr><td>21</td><td><span class="flare_small Xclass">X5.4</span></td><td>2003/10/23</td><td><span class="badge badge-region_mag A"><a href="/en/solar-activity/region/10486">0486</a></span></td><td>08:19</td><td>08:35</td><td>08:49</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/2003/Flares/200310230835X5.4.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/2003/10/23/xray">View archive</a></div></td></tr><tr><td>22</td><td><span class="flare_small Xclass">X5.3</span></td><td>2001/08/25</td><td><span class="badge badge-region_mag BGD"><a href="/en/solar-activity/region/9591">9591</a></span></td><td>16:23</td><td>16:45</td><td>17:04</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/2001/Flares/200108251645X5.3.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/2001/08/25/xray">View archive</a></div></td></tr><tr><td>23</td><td><span class="flare_small Xclass">X4.9</span></td><td>2014/02/25</td><td><span class="badge badge-region_mag A"><a href="/en/solar-activity/region/11990">1990</a></span></td><td>00:39</td><td>00:49</td><td>01:03</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/2014/Flares/201402250049X4.9.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/2014/02/25/xray">View archive</a></div></td></tr><tr><td>24</td><td><span class="flare_small Xclass">X4.9</span></td><td>1998/08/18</td><td><span class="badge badge-region_mag"><a href="/en/solar-activity/region/8307">8307</a></span></td><td>22:10</td><td>22:19</td><td>22:28</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" href="/en/archive/1998/08/18/xray">View archive</a></div></td></tr><tr><td>25</td><td><span class="flare_small Xclass">X4.8</span></td><td>2002/07/23</td><td><span class="badge badge-region_mag B"><a href="/en/solar-activity/region/10039">0039</a></span></td><td>00:18</td><td>00:35</td><td>00:47</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/2002/Flares/200207230035X4.8.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/2002/07/23/xray">View archive</a></div></td></tr><tr><td>26</td><td><span class="flare_small Xclass">X4</span></td><td>2000/11/26</td><td><span class="badge badge-region_mag BG"><a href="/en/solar-activity/region/9236">9236</a></span></td><td>16:34</td><td>16:48</td><td>16:56</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/2000/Flares/200011261648X4.0.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/2000/11/26/xray">View archive</a></div></td></tr><tr><td>27</td><td><span class="flare_small Xclass">X3.9</span></td><td>2003/11/03</td><td><span class="badge badge-region_mag BGD"><a href="/en/solar-activity/region/10488">0488</a></span></td><td>09:43</td><td>09:55</td><td>10:19</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/2003/Flares/200311030955X3.9.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/2003/11/03/xray">View archive</a></div></td></tr><tr><td>28</td><td><span class="flare_small Xclass">X3.9</span></td><td>1998/08/19</td><td><span class="badge badge-region_mag"><a href="/en/solar-activity/region/8307">8307</a></span></td><td>21:35</td><td>21:45</td><td>21:50</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" href="/en/archive/1998/08/19/xray">View archive</a></div></td></tr><tr><td>29</td><td><span class="flare_small Xclass">X3.8</span></td><td>2005/01/17</td><td><span class="badge badge-region_mag BD"><a href="/en/solar-activity/region/10720">0720</a></span></td><td>06:59</td><td>09:52</td><td>10:07</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/2005/Flares/200501170952X3.8.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/2005/01/17/xray">View archive</a></div></td></tr><tr><td>30</td><td><span class="flare_small Xclass">X3.7</span></td><td>1998/11/22</td><td><span class="badge badge-region_mag B"><a href="/en/solar-activity/region/8384">8384</a></span></td><td>06:30</td><td>06:42</td><td>06:49</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/1998/Flares/199811220642X3.7.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/1998/11/22/xray">View archive</a></div></td></tr><tr><td>31</td><td><span class="flare_small Xclass">X3.6</span></td><td>2005/09/09</td><td><span class="badge badge-region_mag BG"><a href="/en/solar-activity/region/10808">0808</a></span></td><td>09:42</td><td>09:59</td><td>10:08</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/2005/Flares/200509090959X3.6.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/2005/09/09/xray">View archive</a></div></td></tr><tr><td>32</td><td><span class="flare_small Xclass">X3.6</span></td><td>2004/07/16</td><td><span class="badge badge-region_mag BGD"><a href="/en/solar-activity/region/10649">0649</a></span></td><td>13:49</td><td>13:55</td><td>14:01</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/2004/Flares/200407161355X3.6.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/2004/07/16/xray">View archive</a></div></td></tr><tr><td>33</td><td><span class="flare_small Xclass">X3.6</span></td><td>2003/05/28</td><td><span class="badge badge-region_mag BGD"><a href="/en/solar-activity/region/10365">0365</a></span></td><td>00:17</td><td>00:27</td><td>00:39</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/2003/Flares/200305280027X3.6.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/2003/05/28/xray">View archive</a></div></td></tr><tr><td>34</td><td><span class="flare_small Xclass">X3.4</span></td><td>2006/12/13</td><td><span class="badge badge-region_mag BGD"><a href="/en/solar-activity/region/10930">0930</a></span></td><td>02:14</td><td>02:40</td><td>02:57</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/2006/Flares/200612130240X3.4.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/2006/12/13/xray">View archive</a></div></td></tr><tr><td>35</td><td><span class="flare_small Xclass">X3.4</span></td><td>2001/12/28</td><td><span class="badge badge-region_mag"><a href="/en/solar-activity/region/9767">9767</a></span></td><td>20:02</td><td>20:45</td><td>21:32</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/2001/Flares/200112282045X3.4.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/2001/12/28/xray">View archive</a></div></td></tr><tr><td>36</td><td><span class="flare_small Xclass">X3.3</span></td><td>2013/11/05</td><td><span class="badge badge-region_mag BGD"><a href="/en/solar-activity/region/11890">1890</a></span></td><td>22:07</td><td>22:12</td><td>22:15</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/2013/Flares/201311052212X3.3.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/2013/11/05/xray">View archive</a></div></td></tr><tr><td>37</td><td><span class="flare_small Xclass">X3.3</span></td><td>2002/07/20</td><td><span class="badge badge-region_mag"><a href="/en/solar-activity/region/10039">0039</a></span></td><td>21:04</td><td>21:30</td><td>21:54</td><td><div class="btn-group"><a class="btn btn-xs btn-outline-dark" data-fancybox="" href="/images/Archief/2002/Flares/200207202130X3.3.mp4"><i aria-hidden="true" class="far fa-play-circle"></i> Movie</a><a class="btn btn-xs btn-outline-dark" href="/en/archive/2002/07/20/xray">View archive</a></div></td></tr><tr><td>38</td><td><span class="flare_small Xclass">X3.3</span></td><td>1998/11/28</td><td><span class=

In [5]:
rank = []
x_class = []
date = []
region = []
start_time = []
max_time = []
end_time = []
movie = []

rows = table[0].find_all('tr')
i = 0 
for row in rows:
    if i == 0: # skip the header
        i += 1
        continue
    cols = row.find_all('td')
    rank.append(cols[0].text)
    x_class.append(cols[1].text)
    date.append(cols[2].text)
    region.append(cols[3].text)
    start_time.append(cols[4].text)
    max_time.append(cols[5].text)
    end_time.append(cols[6].text)
    movie.append(cols[7].text)
len(rank), len(x_class), len(date), len(region), len(start_time), len(max_time), len(end_time), len(movie)

(50, 50, 50, 50, 50, 50, 50, 50)

In [6]:
spaceWeatherDataFrame=pd.DataFrame({'Rank':rank,'X_class':x_class,'Date':date,'Region':region,'Start_time':start_time,'Max_time':max_time,'End_time':end_time,'Movie':movie})
spaceWeatherDataFrame

,Rank,X_class,Date,Region,Start_time,Max_time,End_time,Movie
0,1,X28+,2003/11/04,0486,19:29,19:53,20:06,MovieView archive
1,2,X20+,2001/04/02,9393,21:32,21:51,22:03,MovieView archive
2,3,X17.2+,2003/10/28,0486,09:51,11:10,11:24,MovieView archive
3,4,X17+,2005/09/07,0808,17:17,17:40,18:03,MovieView archive
4,5,X14.4,2001/04/15,9415,13:19,13:50,13:55,MovieView archive
5,6,X10,2003/10/29,0486,20:37,20:49,21:01,MovieView archive
6,7,X9.4,1997/11/06,8100,11:49,11:55,12:01,MovieView archive
7,8,X9.3,2017/09/06,2673,11:53,12:02,12:10,MovieView archive
8,9,X9,2006/12/05,0930,10:18,10:35,10:45,MovieView archive
9,10,X8.3,2003/11/02,0486,17:03,17:25,17:39,MovieView archive
10,11,X8.2,2017/09/10,2673,15:35,16:06,16:31,MovieView archive
11,12,X7.1,2005/01/20,0720,06:36,07:01,07:26,MovieView archive
12,13,X6.9,2011/08/09,1263,07:48,08:05,08:08,MovieView archive
13,14,X6.5,2006/12/06,0930,18:29,18:47,19:00,MovieView archive
14,15,X6.2,2005/09/09,0808,19:13,20:04,20:36,MovieView archive
15,16,X6.2,2001/12/13,9733,14:20,14:30,14:35,MovieView archive
16,17,X5.7,2000/07/14,9077,10:03,10:24,10:43,MovieView archive
17,18,X5.6,2001/04/06,9415,19:10,19:21,19:31,MovieView archive
18,19,X5.4,2012/03/07,1429,00:02,00:24,00:40,MovieView archive
19,20,X5.4,2005/09/08,0808,20:52,21:06,21:17,MovieView archive
20,21,X5.4,2003/10/23,0486,08:19,08:35,08:49,MovieView archive
21,22,X5.3,2001/08/25,9591,16:23,16:45,17:04,MovieView archive
22,23,X4.9,2014/02/25,1990,00:39,00:49,01:03,MovieView archive
23,24,X4.9,1998/08/18,8307,22:10,22:19,22:28,View archive
24,25,X4.8,2002/07/23,0039,00:18,00:35,00:47,MovieView archive
25,26,X4,2000/11/26,9236,16:34,16:48,16:56,MovieView archive
26,27,X3.9,2003/11/03,0488,09:43,09:55,10:19,MovieView archive
27,28,X3.9,1998/08/19,8307,21:35,21:45,21:50,View archive
28,29,X3.8,2005/01/17,0720,06:59,09:52,10:07,MovieView archive
29,30,X3.7,1998/11/22,8384,06:30,06:42,06:49,MovieView archive
30,31,X3.6,2005/09/09,0808,09:42,09:59,10:08,MovieView archive
31,32,X3.6,2004/07/16,0649,13:49,13:55,14:01,MovieView archive
32,33,X3.6,2003/05/28,0365,00:17,00:27,00:39,MovieView archive
33,34,X3.4,2006/12/13,0930,02:14,02:40,02:57,MovieView archive
34,35,X3.4,2001/12/28,9767,20:02,20:45,21:32,MovieView archive
35,36,X3.3,2013/11/05,1890,22:07,22:12,22:15,MovieView archive
36,37,X3.3,2002/07/20,0039,21:04,21:30,21:54,MovieView archive
37,38,X3.3,1998/11/28,8395,04:54,05:52,06:13,MovieView archive
38,39,X3.2,2013/05/14,1748,00:00,01:11,01:20,MovieView archive
39,40,X3.1,2014/10/24,2192,21:07,21:41,22:13,MovieView archive
40,41,X3.1,2002/08/24,0069,00:49,01:12,01:31,MovieView archive
41,42,X3,2002/07/15,0030,19:59,20:08,20:14,MovieView archive
42,43,X2.8,2013/05/13,1748,15:48,16:05,16:16,MovieView archive
43,44,X2.8,2001/12/11,9733,07:58,08:08,08:14,MovieView archive
44,45,X2.8,1998/08/18,8307,08:14,08:24,08:32,View archive
45,46,X2.7,2015/05/05,2339,22:05,22:11,22:15,MovieView archive
46,47,X2.7,2003/11/03,0488,01:09,01:30,01:45,MovieView archive
47,48,X2.7,1998/05/06,8210,07:58,08:09,08:20,MovieView archive
48,49,X2.6,2005/01/15,0720,22:25,23:02,23:31,MovieView archive
49,50,X2.6,2001/09/24,9632,09:32,10:38,11:09,MovieView archive

In [7]:
modifiedDataFrame=spaceWeatherDataFrame
modifiedDataFrame.drop(['Movie'],axis=1,inplace=True)
modifiedDataFrame.head()

  Rank X_class        Date Region Start_time Max_time End_time
0    1    X28+  2003/11/04   0486      19:29    19:53    20:06
1    2    X20+  2001/04/02   9393      21:32    21:51    22:03
2    3  X17.2+  2003/10/28   0486      09:51    11:10    11:24
3    4    X17+  2005/09/07   0808      17:17    17:40    18:03
4    5   X14.4  2001/04/15   9415      13:19    13:50    13:55

In [8]:
modifiedDataFrame['Start_time'] = modifiedDataFrame['Date'] + " " + modifiedDataFrame['Start_time']
modifiedDataFrame['End_time'] = modifiedDataFrame['Date'] + " " + modifiedDataFrame['End_time']
modifiedDataFrame['Max_time'] = modifiedDataFrame['Date'] + " " + modifiedDataFrame['Max_time']
modifiedDataFrame.drop(['Date'], axis=1, inplace=True)
modifiedDataFrame.head()

  Rank X_class Region        Start_time          Max_time          End_time
0    1    X28+   0486  2003/11/04 19:29  2003/11/04 19:53  2003/11/04 20:06
1    2    X20+   9393  2001/04/02 21:32  2001/04/02 21:51  2001/04/02 22:03
2    3  X17.2+   0486  2003/10/28 09:51  2003/10/28 11:10  2003/10/28 11:24
3    4    X17+   0808  2005/09/07 17:17  2005/09/07 17:40  2005/09/07 18:03
4    5   X14.4   9415  2001/04/15 13:19  2001/04/15 13:50  2001/04/15 13:55

In [9]:
modifiedDataFrame['Start_time'] = pd.to_datetime(modifiedDataFrame['Start_time'])
modifiedDataFrame['End_time'] = pd.to_datetime(modifiedDataFrame['End_time'])
modifiedDataFrame['Max_time'] = pd.to_datetime(modifiedDataFrame['Max_time'])
modifiedDataFrame[:10]

,Rank,X_class,Region,Start_time,Max_time,End_time
0,1,X28+,0486,2003-11-04 19:29:00,2003-11-04 19:53:00,2003-11-04 20:06:00
1,2,X20+,9393,2001-04-02 21:32:00,2001-04-02 21:51:00,2001-04-02 22:03:00
2,3,X17.2+,0486,2003-10-28 09:51:00,2003-10-28 11:10:00,2003-10-28 11:24:00
3,4,X17+,0808,2005-09-07 17:17:00,2005-09-07 17:40:00,2005-09-07 18:03:00
4,5,X14.4,9415,2001-04-15 13:19:00,2001-04-15 13:50:00,2001-04-15 13:55:00
5,6,X10,0486,2003-10-29 20:37:00,2003-10-29 20:49:00,2003-10-29 21:01:00
6,7,X9.4,8100,1997-11-06 11:49:00,1997-11-06 11:55:00,1997-11-06 12:01:00
7,8,X9.3,2673,2017-09-06 11:53:00,2017-09-06 12:02:00,2017-09-06 12:10:00
8,9,X9,0930,2006-12-05 10:18:00,2006-12-05 10:35:00,2006-12-05 10:45:00
9,10,X8.3,0486,2003-11-02 17:03:00,2003-11-02 17:25:00,2003-11-02 17:39:00

In [10]:
modifiedDataFrame.dtypes

Rank                  object
X_class               object
Region                object
Start_time    datetime64[ns]
Max_time      datetime64[ns]
End_time      datetime64[ns]
dtype: object

In [11]:
for col in modifiedDataFrame.columns[:3]:
    print(modifiedDataFrame[col].str.contains('-').sum())

0
0
0

In [12]:
modifiedDataFrame.to_csv('first.csv')

# Nasa

In [13]:
reb = requests.get("http://www.hcbravo.org/IntroDataSci/misc/waves_type2.html")
reb.text[:1000]

'<html><body>\n<h2>Wind/WAVES type II bursts and CMEs</h2>\n<a href="waves_type2_description.htm">A Brief Description</a>\n<pre>\nNOTE: List includes DH type II bursts observed by Wind spacecraft, \nbut after STEREO launch on Oct 2006 the start and end times and \nfrequencies of bursts are determined using both Wind and STEREO \nobservations\n\n=================================================================================================\n                DH Type II                       Flare                     CME                   \n----------------------------------------   -----------------   --------------------------   Plots\nStart            End          Frequency     Loc   NOAA  Imp    Date  Time CPA  Width  Spd        \n(1)        (2)   (3)   (4)   (5)    (6)     (7)    (8)  (9)    (10)  (11) (12)  (13) (14)   (15) \n=================================================================================================\n1997/04/01 14:00 04/01 14:15  <a href="http://cdaw.gsfc.nasa.gov/CME_list/d'

In [14]:
page=BeautifulSoup(reb.text)
page.prettify()[:1000]

'<html>\n <body>\n  <h2>\n   Wind/WAVES type II bursts and CMEs\n  </h2>\n  <a href="waves_type2_description.htm">\n   A Brief Description\n  </a>\n  <pre>\nNOTE: List includes DH type II bursts observed by Wind spacecraft, \nbut after STEREO launch on Oct 2006 the start and end times and \nfrequencies of bursts are determined using both Wind and STEREO \nobservations\n\n=================================================================================================\n                DH Type II                       Flare                     CME                   \n----------------------------------------   -----------------   --------------------------   Plots\nStart            End          Frequency     Loc   NOAA  Imp    Date  Time CPA  Width  Spd        \n(1)        (2)   (3)   (4)   (5)    (6)     (7)    (8)  (9)    (10)  (11) (12)  (13) (14)   (15) \n=================================================================================================\n1997/04/01 14:00 04/01 14:15  <a href="http://cdaw.gs'

In [15]:
rex=r'\d+/.*'
l=re.findall(rex,page.text)
newList=[]
for i in l:
    newList.append(i.split())
newList[0]

['1997/04/01',
 '14:00',
 '04/01',
 '14:15',
 '8000',
 '4000',
 'S25E16',
 '8026',
 'M1.3',
 '04/01',
 '15:18',
 '74',
 '79',
 '312',
 'PHTX']

In [16]:
startDate=[]
startTime=[]
endDate=[]
endTime=[]
startFrequency=[]
endFrequency=[]
flare_Location=[]
flare_region=[]
importance=[]
CME_Date=[]
CME_Time=[]
CPA=[]
width = []
speed = []
for i in newList:
    startDate.append(i[0])
    startTime.append(i[1])
    endDate.append(i[2])
    endTime.append(i[3])
    startFrequency.append(i[4])
    endFrequency.append(i[5])
    flare_Location.append(i[6])
    flare_region.append(i[7])
    importance.append(i[8])
    CME_Date.append(i[9])
    CME_Time.append(i[10])
    CPA.append(i[11])
    width.append(i[12])
    speed.append(i[13])
df = pd.DataFrame({'startDate':startDate,'startTime':startTime,'endDate':endDate,
                   'endTime':endTime,'startFrequency':startFrequency,'endFrequency':endFrequency,
                   'flare_Location': flare_Location,'flare_region':flare_region,'importance':importance,
                   'CME_Date':CME_Date,'CME_Time':CME_Time, 'width':width, 'speed':speed, 'CPA':CPA})
df[:100]

,startDate,startTime,endDate,endTime,startFrequency,endFrequency,flare_Location,flare_region,importance,CME_Date,CME_Time,width,speed,CPA
0,1997/04/01,14:00,04/01,14:15,8000,4000,S25E16,8026,M1.3,04/01,15:18,79,312,74
1,1997/04/07,14:30,04/07,17:30,11000,1000,S28E19,8027,C6.8,04/07,14:27,360,878,Halo
2,1997/05/12,05:15,05/14,16:00,12000,80,N21W08,8038,C1.3,05/12,05:30,360,464,Halo
3,1997/05/21,20:20,05/21,22:00,5000,500,N05W12,8040,M1.3,05/21,21:00,165,296,263
4,1997/09/23,21:53,09/23,22:16,6000,2000,S29E25,8088,C1.4,09/23,22:02,155,712,133
5,1997/11/03,05:15,11/03,12:00,14000,250,S20W13,8100,C8.6,11/03,05:28,109,227,240
6,1997/11/03,10:30,11/03,11:30,14000,5000,S16W21,8100,M4.2,11/03,11:11,122,352,233
7,1997/11/04,06:00,11/05,04:30,14000,100,S14W33,8100,X2.1,11/04,06:10,360,785,Halo
8,1997/11/06,12:20,11/07,08:30,14000,100,S18W63,8100,X9.4,11/06,12:10,360,1556,Halo
9,1997/11/27,13:30,11/27,14:00,14000,7000,N17E63,8113,X2.6,11/27,13:56,91,441,98
10,1997/12/12,22:45,12/12,23:20,14000,8000,N25W52,8116,B9.4,12/13,00:26,73,191,278
11,1998/01/25,15:03,01/25,15:18,14000,10000,N21E25,8141,C1.1,01/25,15:26,360,693,Halo
12,1998/03/29,03:40,03/29,03:52,14000,7000,SW90,-----,----,03/29,03:48,360,1397,Halo
13,1998/04/20,10:25,04/22,06:00,10000,35,S22W90,8194,M1.4,04/20,10:07,165,1863,284
14,1998/04/23,06:00,04/23,15:30,14000,200,S17E90,8210,X1.2,04/23,05:55,360,1691,Halo
15,1998/04/24,09:17,04/24,09:25,4700,2600,S10E90,8210,C8.9,04/24,08:55,84,1184,100
16,1998/04/27,09:20,04/27,10:00,10000,1000,S16E50,8210,X1.0,04/27,08:56,360,1385,Halo
17,1998/04/29,16:30,04/29,17:00,10000,2000,S18E20,8210,M6.8,04/29,16:58,360,1374,Halo
18,1998/05/02,14:25,05/02,14:50,5000,3000,S15W15,8210,X1.1,05/02,14:06,360,938,Halo
19,1998/05/06,08:25,05/06,08:35,14000,5000,S11W65,8210,X2.7,05/06,08:29,190,1099,309
20,1998/05/09,03:35,05/09,10:00,9000,400,S14W89,8210,M7.7,05/09,03:35,178,2331,262
21,1998/05/11,21:40,05/11,22:00,10000,1000,N32W90,8214,B6.6,05/11,21:55,>301,830,208
22,1998/05/19,10:00,05/19,11:30,14000,3000,N29W46,8222,B7.9,05/19,10:27,139,801,268
23,1998/05/27,13:30,05/27,14:20,4000,1000,N19W62,8226,C7.5,05/27,13:45,268,878,175
24,1998/06/11,10:15,06/11,10:20,8000,4000,N16E86,8243,M1.4,06/11,10:28,177,1223,123
25,1998/06/16,18:20,06/17,21:00,12000,50,S22W90,8232,M1.0,06/16,18:27,281,1484,341
26,1998/06/20,19:39,06/20,20:00,2600,1800,Back,-----,----,06/20,18:20,360,964,Halo
27,1998/06/22,07:15,06/22,09:20,6000,2000,N16W46,8243,C2.9,06/22,05:01,59,206,265
28,1998/11/02,14:00,11/02,14:40,14000,4000,S25E47,8373,C4.4,11/02,14:18,169,661,116
29,1998/11/05,22:00,11/07,08:00,5000,50,N22W18,8375,M8.4,11/05,20:44,360,1118,Halo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,2000/05/12,23:34,05/12,23:42,14000,7000,E90b,-----,----,05/12,23:26,360,2604,Halo
71,2000/05/15,16:47,05/16,14:00,4800,40,S24W67,8993,C7.8,05/15,16:26,>165,1212,257
72,2000/06/02,22:00,06/02,22:15,14000,8000,N16E60,9026,M7.6,06/02,21:30,104,547,69
73,2000/06/06,15:20,06/08,09:00,14000,40,N20E18,9026,X2.3,06/06,15:54,360,1119,Halo
74,2000/06/10,17:15,06/10,18:45,10000,1000,N22W38,9026,M5.2,06/10,17:08,360,1108,Halo
75,2000/06/15,19:52,06/15,19:56,5000,2500,N20W65,9041,M1.8,06/15,20:06,116,1081,298
76,2000/06/17,03:00,06/17,04:15,14000,1000,N22W72,9041,M3.5,06/17,03:28,133,857,298
77,2000/06/19,01:19,06/19,01:22,3800,1900,N42E60,-----,----,06/18,21:30,49,459,8
78,2000/06/23,14:40,06/22,15:05,14000,2000,N26W72,9042,M3.0,06/23,14:54,>198,847,282
79,2000/06/25,08:10,06/25,09:00,12000,2500,N16W55,9046,M1.9,06/25,07:54,165,1617,262
80,2000/07/10,22:00,07/10,23:30,14000,1000,N18E49,9077,M5.7,07/10,21:50,>289,1352,67
81,2000/07/11,13:00,07/11,13:30,12000,1000,N18E27,9077,X1.0,07/11,13:27,360,1078,Halo
82,2000/07/12,20:05,07/12,20:35,6000,1000,N19W61,9070,M1.5,07/12,20:30,101,820,281
83,2000/07/14,10:30,07/15,14:30,14000,80,N22W07,9077,X5.7,07/14,10:54,360,1674,Halo
84,2000/07/22,11:45,07/22,12:45,14000,2000,N14W56,9085,M3.7,07/22,11:54,>229,1230,259
85,2000/08/11,11:35,08/11,11:59,2800,2000,NW90b,-----,----,08/11,07:31,70,1071,273
86,2000/09/12,12:00,09/13,12:20,14000,60,S19W06,DSF,M1.0,09/12,11:54,360,1550,Halo
87,2000/09/12,18:15,09/12,19:00,2000,1000,NE90b,-----,----,09/12,17:30,360,1053,Halo
88,2000/09/16,04:30,09/16,10:30,14000,400,N14W07,9165,M5.9,09/16,05:18,360,1215,Halo
89,2000/09/19,08:45,09/19,10:20,12000,1500,N14W46,9165,M5.1,09/19,08:50,76,766,283
90,2000/09/25,02:20,09/25,03:00,14000,1000,N09W18,9169,M1.8,09/25,02:50,360,587,Halo
91,2000/10/05,22:10,10/05,22:35,5000,1250,N25W90,9177,----,10/05,18:26,86,1046,323
92,2000/10/16,07:10,10/16,08:00,14000,1000,N03W90,9182,M2.5,10/16,07:27,360,1336,Halo
93,2000/10/25,09:30,10/25,24:00,10000,300,N09W63,9199,C4.0,10/25,08:26,360,770,Halo
94,2000/11/03,18:35,11/03,18:45,4000,2500,N02W02,9213,C3.2,11/03,18:26,360,291,Halo
95,2000/11/08,23:20,11/09,12:00,4000,200,N10W77,9213,M7.4,11/08,23:06,>170,1738,271
96,2000/11/09,16:15,11/11,04:00,10000,40,S11E10,9221,M1.0,--/--,--:--,----,----,----
97,2000/11/12,14:25,11/12,14:40,3000,2000,S14E05,9227,C4.4,11/12,14:50,50,581,257
98,2000/11/23,08:16,11/23,08:35,14000,9000,S26W40,9238,C5.4,11/23,06:06,360,492,Halo
99,2000/11/23,21:00,11/23,21:06,3500,3000,S20E60,9239,C7.9,11/23,21:30,148,1198,124

In [17]:
len(df.columns)

14

In [18]:
df.columns

Index(['startDate', 'startTime', 'endDate', 'endTime', 'startFrequency',
       'endFrequency', 'flare_Location', 'flare_region', 'importance',
       'CME_Date', 'CME_Time', 'width', 'speed', 'CPA'],
      dtype='object')

In [19]:
df[:100]

,startDate,startTime,endDate,endTime,startFrequency,endFrequency,flare_Location,flare_region,importance,CME_Date,CME_Time,width,speed,CPA
0,1997/04/01,14:00,04/01,14:15,8000,4000,S25E16,8026,M1.3,04/01,15:18,79,312,74
1,1997/04/07,14:30,04/07,17:30,11000,1000,S28E19,8027,C6.8,04/07,14:27,360,878,Halo
2,1997/05/12,05:15,05/14,16:00,12000,80,N21W08,8038,C1.3,05/12,05:30,360,464,Halo
3,1997/05/21,20:20,05/21,22:00,5000,500,N05W12,8040,M1.3,05/21,21:00,165,296,263
4,1997/09/23,21:53,09/23,22:16,6000,2000,S29E25,8088,C1.4,09/23,22:02,155,712,133
5,1997/11/03,05:15,11/03,12:00,14000,250,S20W13,8100,C8.6,11/03,05:28,109,227,240
6,1997/11/03,10:30,11/03,11:30,14000,5000,S16W21,8100,M4.2,11/03,11:11,122,352,233
7,1997/11/04,06:00,11/05,04:30,14000,100,S14W33,8100,X2.1,11/04,06:10,360,785,Halo
8,1997/11/06,12:20,11/07,08:30,14000,100,S18W63,8100,X9.4,11/06,12:10,360,1556,Halo
9,1997/11/27,13:30,11/27,14:00,14000,7000,N17E63,8113,X2.6,11/27,13:56,91,441,98
10,1997/12/12,22:45,12/12,23:20,14000,8000,N25W52,8116,B9.4,12/13,00:26,73,191,278
11,1998/01/25,15:03,01/25,15:18,14000,10000,N21E25,8141,C1.1,01/25,15:26,360,693,Halo
12,1998/03/29,03:40,03/29,03:52,14000,7000,SW90,-----,----,03/29,03:48,360,1397,Halo
13,1998/04/20,10:25,04/22,06:00,10000,35,S22W90,8194,M1.4,04/20,10:07,165,1863,284
14,1998/04/23,06:00,04/23,15:30,14000,200,S17E90,8210,X1.2,04/23,05:55,360,1691,Halo
15,1998/04/24,09:17,04/24,09:25,4700,2600,S10E90,8210,C8.9,04/24,08:55,84,1184,100
16,1998/04/27,09:20,04/27,10:00,10000,1000,S16E50,8210,X1.0,04/27,08:56,360,1385,Halo
17,1998/04/29,16:30,04/29,17:00,10000,2000,S18E20,8210,M6.8,04/29,16:58,360,1374,Halo
18,1998/05/02,14:25,05/02,14:50,5000,3000,S15W15,8210,X1.1,05/02,14:06,360,938,Halo
19,1998/05/06,08:25,05/06,08:35,14000,5000,S11W65,8210,X2.7,05/06,08:29,190,1099,309
20,1998/05/09,03:35,05/09,10:00,9000,400,S14W89,8210,M7.7,05/09,03:35,178,2331,262
21,1998/05/11,21:40,05/11,22:00,10000,1000,N32W90,8214,B6.6,05/11,21:55,>301,830,208
22,1998/05/19,10:00,05/19,11:30,14000,3000,N29W46,8222,B7.9,05/19,10:27,139,801,268
23,1998/05/27,13:30,05/27,14:20,4000,1000,N19W62,8226,C7.5,05/27,13:45,268,878,175
24,1998/06/11,10:15,06/11,10:20,8000,4000,N16E86,8243,M1.4,06/11,10:28,177,1223,123
25,1998/06/16,18:20,06/17,21:00,12000,50,S22W90,8232,M1.0,06/16,18:27,281,1484,341
26,1998/06/20,19:39,06/20,20:00,2600,1800,Back,-----,----,06/20,18:20,360,964,Halo
27,1998/06/22,07:15,06/22,09:20,6000,2000,N16W46,8243,C2.9,06/22,05:01,59,206,265
28,1998/11/02,14:00,11/02,14:40,14000,4000,S25E47,8373,C4.4,11/02,14:18,169,661,116
29,1998/11/05,22:00,11/07,08:00,5000,50,N22W18,8375,M8.4,11/05,20:44,360,1118,Halo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,2000/05/12,23:34,05/12,23:42,14000,7000,E90b,-----,----,05/12,23:26,360,2604,Halo
71,2000/05/15,16:47,05/16,14:00,4800,40,S24W67,8993,C7.8,05/15,16:26,>165,1212,257
72,2000/06/02,22:00,06/02,22:15,14000,8000,N16E60,9026,M7.6,06/02,21:30,104,547,69
73,2000/06/06,15:20,06/08,09:00,14000,40,N20E18,9026,X2.3,06/06,15:54,360,1119,Halo
74,2000/06/10,17:15,06/10,18:45,10000,1000,N22W38,9026,M5.2,06/10,17:08,360,1108,Halo
75,2000/06/15,19:52,06/15,19:56,5000,2500,N20W65,9041,M1.8,06/15,20:06,116,1081,298
76,2000/06/17,03:00,06/17,04:15,14000,1000,N22W72,9041,M3.5,06/17,03:28,133,857,298
77,2000/06/19,01:19,06/19,01:22,3800,1900,N42E60,-----,----,06/18,21:30,49,459,8
78,2000/06/23,14:40,06/22,15:05,14000,2000,N26W72,9042,M3.0,06/23,14:54,>198,847,282
79,2000/06/25,08:10,06/25,09:00,12000,2500,N16W55,9046,M1.9,06/25,07:54,165,1617,262
80,2000/07/10,22:00,07/10,23:30,14000,1000,N18E49,9077,M5.7,07/10,21:50,>289,1352,67
81,2000/07/11,13:00,07/11,13:30,12000,1000,N18E27,9077,X1.0,07/11,13:27,360,1078,Halo
82,2000/07/12,20:05,07/12,20:35,6000,1000,N19W61,9070,M1.5,07/12,20:30,101,820,281
83,2000/07/14,10:30,07/15,14:30,14000,80,N22W07,9077,X5.7,07/14,10:54,360,1674,Halo
84,2000/07/22,11:45,07/22,12:45,14000,2000,N14W56,9085,M3.7,07/22,11:54,>229,1230,259
85,2000/08/11,11:35,08/11,11:59,2800,2000,NW90b,-----,----,08/11,07:31,70,1071,273
86,2000/09/12,12:00,09/13,12:20,14000,60,S19W06,DSF,M1.0,09/12,11:54,360,1550,Halo
87,2000/09/12,18:15,09/12,19:00,2000,1000,NE90b,-----,----,09/12,17:30,360,1053,Halo
88,2000/09/16,04:30,09/16,10:30,14000,400,N14W07,9165,M5.9,09/16,05:18,360,1215,Halo
89,2000/09/19,08:45,09/19,10:20,12000,1500,N14W46,9165,M5.1,09/19,08:50,76,766,283
90,2000/09/25,02:20,09/25,03:00,14000,1000,N09W18,9169,M1.8,09/25,02:50,360,587,Halo
91,2000/10/05,22:10,10/05,22:35,5000,1250,N25W90,9177,----,10/05,18:26,86,1046,323
92,2000/10/16,07:10,10/16,08:00,14000,1000,N03W90,9182,M2.5,10/16,07:27,360,1336,Halo
93,2000/10/25,09:30,10/25,24:00,10000,300,N09W63,9199,C4.0,10/25,08:26,360,770,Halo
94,2000/11/03,18:35,11/03,18:45,4000,2500,N02W02,9213,C3.2,11/03,18:26,360,291,Halo
95,2000/11/08,23:20,11/09,12:00,4000,200,N10W77,9213,M7.4,11/08,23:06,>170,1738,271
96,2000/11/09,16:15,11/11,04:00,10000,40,S11E10,9221,M1.0,--/--,--:--,----,----,----
97,2000/11/12,14:25,11/12,14:40,3000,2000,S14E05,9227,C4.4,11/12,14:50,50,581,257
98,2000/11/23,08:16,11/23,08:35,14000,9000,S26W40,9238,C5.4,11/23,06:06,360,492,Halo
99,2000/11/23,21:00,11/23,21:06,3500,3000,S20E60,9239,C7.9,11/23,21:30,148,1198,124

In [20]:
missing_cols = []
for col in df.columns:
    s = df[col].str.contains('-').sum()
    print(col, s)
    if s>0:
        missing_cols.append(col)

startDate 0
startTime 0
endDate 0
endTime 0
startFrequency 0
endFrequency 0
flare_Location 6
flare_region 83
importance 105
CME_Date 20
CME_Time 20
width 20
speed 20
CPA 21

In [21]:
missing_cols

['flare_Location',
 'flare_region',
 'importance',
 'CME_Date',
 'CME_Time',
 'width',
 'speed',
 'CPA']

In [22]:
df[df[col].str.contains('-')]

,startDate,startTime,endDate,endTime,startFrequency,endFrequency,flare_Location,flare_region,importance,CME_Date,CME_Time,width,speed,CPA
96,2000/11/09,16:15,11/11,04:00,10000,40,S11E10,9221,M1.0,--/--,--:--,----,----,----
149,2001/10/09,11:20,10/09,11:55,14000,2000,S28E08,9653,----,--/--,--:--,----,----,----
150,2001/10/09,13:10,10/09,23:00,5000,50,BACK,-----,----,--/--,--:--,----,----,----
229,2003/07/10,14:10,07/10,16:10,4000,400,N13W90,10397,M3.6,--/--,--:--,----,----,----
250,2004/01/05,03:40,01/05,03:50,9000,2500,S12E38,10536,M6.9,--/--,--:--,----,----,----
261,2004/06/22,22:07,06/22,22:30,10000,7000,S12W24,10635,C1.7,--/--,--:--,----,----,----
262,2004/06/23,06:30,06/23,08:55,14000,5000,S09W21,10635,C2.5,--/--,--:--,----,----,----
269,2004/09/19,17:15,09/19,18:15,14000,2500,N03W58,10672,M1.9,--/--,--:--,----,----,----
284,2005/01/04,11:20,01/04,11:35,13000,6000,N05W11,10715,C7.3,--/--,--:--,----,----,----
298,2005/06/16,20:25,06/16,21:40,9000,1000,N08W90,10775,M4.0,--/--,--:--,----,----,----
318,2005/09/07,18:05,09/08,00:00,12000,200,S11E77,10808,X1.7,--/--,--:--,----,----,----
330,2006/12/05,10:50,12/05,20:00,14000,250,S07E68,10930,X9.0,--/--,--:--,----,----,----
331,2006/12/06,02:00,12/06,03:30,1000,200,S07E69,10930,M1.1,--/--,--:--,----,----,----
332,2006/12/06,08:30,12/06,09:45,4000,600,S04E63,10930,M6.0,--/--,--:--,----,----,----
333,2006/12/06,19:00,12/08,24:00,16000,30,S05E64,10930,X6.5,--/--,--:--,----,----,----
341,2010/08/01,09:20,08/01,17:30,2000,700,N20E36,11092,C3.2,--/--,--:--,----,----,----
419,2013/10/13,18:47,10/14,05:15,2100,600,------,-----,----,10/13,14:12,83,293,----
432,2013/12/05,20:48,12/05,21:35,14000,2500,------,-----,----,--/--,--:--,---,----,----
437,2014/01/04,17:41,01/04,18:47,9000,100,------,-----,----,--/--,--:--,---,----,----
438,2014/01/04,19:03,01/05,09:00,6500,100,------,-----,----,--/--,--:--,---,----,----
451,2014/04/02,18:49,04/03,06:40,2400,200,------,-----,----,--/--,--:--,---,----,----

# STOP !!!!

In [23]:
new_df = df.copy()

In [24]:
new_df.startDate.str.contains('nan').sum(), new_df.endDate.str.contains('nan').sum()

(0, 0)

In [25]:
col='CPA'

In [26]:
new_df.loc[new_df[col].str.contains('-'), 'CPA'] = 'nan'

In [27]:
new_df.startDate.str.contains('nan').sum(), new_df.endDate.str.contains('nan').sum()

(0, 0)

In [28]:
new_df[:100]

,startDate,startTime,endDate,endTime,startFrequency,endFrequency,flare_Location,flare_region,importance,CME_Date,CME_Time,width,speed,CPA
0,1997/04/01,14:00,04/01,14:15,8000,4000,S25E16,8026,M1.3,04/01,15:18,79,312,74
1,1997/04/07,14:30,04/07,17:30,11000,1000,S28E19,8027,C6.8,04/07,14:27,360,878,Halo
2,1997/05/12,05:15,05/14,16:00,12000,80,N21W08,8038,C1.3,05/12,05:30,360,464,Halo
3,1997/05/21,20:20,05/21,22:00,5000,500,N05W12,8040,M1.3,05/21,21:00,165,296,263
4,1997/09/23,21:53,09/23,22:16,6000,2000,S29E25,8088,C1.4,09/23,22:02,155,712,133
5,1997/11/03,05:15,11/03,12:00,14000,250,S20W13,8100,C8.6,11/03,05:28,109,227,240
6,1997/11/03,10:30,11/03,11:30,14000,5000,S16W21,8100,M4.2,11/03,11:11,122,352,233
7,1997/11/04,06:00,11/05,04:30,14000,100,S14W33,8100,X2.1,11/04,06:10,360,785,Halo
8,1997/11/06,12:20,11/07,08:30,14000,100,S18W63,8100,X9.4,11/06,12:10,360,1556,Halo
9,1997/11/27,13:30,11/27,14:00,14000,7000,N17E63,8113,X2.6,11/27,13:56,91,441,98
10,1997/12/12,22:45,12/12,23:20,14000,8000,N25W52,8116,B9.4,12/13,00:26,73,191,278
11,1998/01/25,15:03,01/25,15:18,14000,10000,N21E25,8141,C1.1,01/25,15:26,360,693,Halo
12,1998/03/29,03:40,03/29,03:52,14000,7000,SW90,-----,----,03/29,03:48,360,1397,Halo
13,1998/04/20,10:25,04/22,06:00,10000,35,S22W90,8194,M1.4,04/20,10:07,165,1863,284
14,1998/04/23,06:00,04/23,15:30,14000,200,S17E90,8210,X1.2,04/23,05:55,360,1691,Halo
15,1998/04/24,09:17,04/24,09:25,4700,2600,S10E90,8210,C8.9,04/24,08:55,84,1184,100
16,1998/04/27,09:20,04/27,10:00,10000,1000,S16E50,8210,X1.0,04/27,08:56,360,1385,Halo
17,1998/04/29,16:30,04/29,17:00,10000,2000,S18E20,8210,M6.8,04/29,16:58,360,1374,Halo
18,1998/05/02,14:25,05/02,14:50,5000,3000,S15W15,8210,X1.1,05/02,14:06,360,938,Halo
19,1998/05/06,08:25,05/06,08:35,14000,5000,S11W65,8210,X2.7,05/06,08:29,190,1099,309
20,1998/05/09,03:35,05/09,10:00,9000,400,S14W89,8210,M7.7,05/09,03:35,178,2331,262
21,1998/05/11,21:40,05/11,22:00,10000,1000,N32W90,8214,B6.6,05/11,21:55,>301,830,208
22,1998/05/19,10:00,05/19,11:30,14000,3000,N29W46,8222,B7.9,05/19,10:27,139,801,268
23,1998/05/27,13:30,05/27,14:20,4000,1000,N19W62,8226,C7.5,05/27,13:45,268,878,175
24,1998/06/11,10:15,06/11,10:20,8000,4000,N16E86,8243,M1.4,06/11,10:28,177,1223,123
25,1998/06/16,18:20,06/17,21:00,12000,50,S22W90,8232,M1.0,06/16,18:27,281,1484,341
26,1998/06/20,19:39,06/20,20:00,2600,1800,Back,-----,----,06/20,18:20,360,964,Halo
27,1998/06/22,07:15,06/22,09:20,6000,2000,N16W46,8243,C2.9,06/22,05:01,59,206,265
28,1998/11/02,14:00,11/02,14:40,14000,4000,S25E47,8373,C4.4,11/02,14:18,169,661,116
29,1998/11/05,22:00,11/07,08:00,5000,50,N22W18,8375,M8.4,11/05,20:44,360,1118,Halo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,2000/05/12,23:34,05/12,23:42,14000,7000,E90b,-----,----,05/12,23:26,360,2604,Halo
71,2000/05/15,16:47,05/16,14:00,4800,40,S24W67,8993,C7.8,05/15,16:26,>165,1212,257
72,2000/06/02,22:00,06/02,22:15,14000,8000,N16E60,9026,M7.6,06/02,21:30,104,547,69
73,2000/06/06,15:20,06/08,09:00,14000,40,N20E18,9026,X2.3,06/06,15:54,360,1119,Halo
74,2000/06/10,17:15,06/10,18:45,10000,1000,N22W38,9026,M5.2,06/10,17:08,360,1108,Halo
75,2000/06/15,19:52,06/15,19:56,5000,2500,N20W65,9041,M1.8,06/15,20:06,116,1081,298
76,2000/06/17,03:00,06/17,04:15,14000,1000,N22W72,9041,M3.5,06/17,03:28,133,857,298
77,2000/06/19,01:19,06/19,01:22,3800,1900,N42E60,-----,----,06/18,21:30,49,459,8
78,2000/06/23,14:40,06/22,15:05,14000,2000,N26W72,9042,M3.0,06/23,14:54,>198,847,282
79,2000/06/25,08:10,06/25,09:00,12000,2500,N16W55,9046,M1.9,06/25,07:54,165,1617,262
80,2000/07/10,22:00,07/10,23:30,14000,1000,N18E49,9077,M5.7,07/10,21:50,>289,1352,67
81,2000/07/11,13:00,07/11,13:30,12000,1000,N18E27,9077,X1.0,07/11,13:27,360,1078,Halo
82,2000/07/12,20:05,07/12,20:35,6000,1000,N19W61,9070,M1.5,07/12,20:30,101,820,281
83,2000/07/14,10:30,07/15,14:30,14000,80,N22W07,9077,X5.7,07/14,10:54,360,1674,Halo
84,2000/07/22,11:45,07/22,12:45,14000,2000,N14W56,9085,M3.7,07/22,11:54,>229,1230,259
85,2000/08/11,11:35,08/11,11:59,2800,2000,NW90b,-----,----,08/11,07:31,70,1071,273
86,2000/09/12,12:00,09/13,12:20,14000,60,S19W06,DSF,M1.0,09/12,11:54,360,1550,Halo
87,2000/09/12,18:15,09/12,19:00,2000,1000,NE90b,-----,----,09/12,17:30,360,1053,Halo
88,2000/09/16,04:30,09/16,10:30,14000,400,N14W07,9165,M5.9,09/16,05:18,360,1215,Halo
89,2000/09/19,08:45,09/19,10:20,12000,1500,N14W46,9165,M5.1,09/19,08:50,76,766,283
90,2000/09/25,02:20,09/25,03:00,14000,1000,N09W18,9169,M1.8,09/25,02:50,360,587,Halo
91,2000/10/05,22:10,10/05,22:35,5000,1250,N25W90,9177,----,10/05,18:26,86,1046,323
92,2000/10/16,07:10,10/16,08:00,14000,1000,N03W90,9182,M2.5,10/16,07:27,360,1336,Halo
93,2000/10/25,09:30,10/25,24:00,10000,300,N09W63,9199,C4.0,10/25,08:26,360,770,Halo
94,2000/11/03,18:35,11/03,18:45,4000,2500,N02W02,9213,C3.2,11/03,18:26,360,291,Halo
95,2000/11/08,23:20,11/09,12:00,4000,200,N10W77,9213,M7.4,11/08,23:06,>170,1738,271
96,2000/11/09,16:15,11/11,04:00,10000,40,S11E10,9221,M1.0,--/--,--:--,----,----,nan
97,2000/11/12,14:25,11/12,14:40,3000,2000,S14E05,9227,C4.4,11/12,14:50,50,581,257
98,2000/11/23,08:16,11/23,08:35,14000,9000,S26W40,9238,C5.4,11/23,06:06,360,492,Halo
99,2000/11/23,21:00,11/23,21:06,3500,3000,S20E60,9239,C7.9,11/23,21:30,148,1198,124

In [29]:
new_df.startDate.str.contains('nan').sum(), new_df.endDate.str.contains('nan').sum()

(0, 0)

In [30]:
# replace nan
for col in df.columns:
    new_df.loc[new_df[col].str.contains('-'), col] = 'nan'

In [31]:
new_df[:100]

,startDate,startTime,endDate,endTime,startFrequency,endFrequency,flare_Location,flare_region,importance,CME_Date,CME_Time,width,speed,CPA
0,1997/04/01,14:00,04/01,14:15,8000,4000,S25E16,8026,M1.3,04/01,15:18,79,312,74
1,1997/04/07,14:30,04/07,17:30,11000,1000,S28E19,8027,C6.8,04/07,14:27,360,878,Halo
2,1997/05/12,05:15,05/14,16:00,12000,80,N21W08,8038,C1.3,05/12,05:30,360,464,Halo
3,1997/05/21,20:20,05/21,22:00,5000,500,N05W12,8040,M1.3,05/21,21:00,165,296,263
4,1997/09/23,21:53,09/23,22:16,6000,2000,S29E25,8088,C1.4,09/23,22:02,155,712,133
5,1997/11/03,05:15,11/03,12:00,14000,250,S20W13,8100,C8.6,11/03,05:28,109,227,240
6,1997/11/03,10:30,11/03,11:30,14000,5000,S16W21,8100,M4.2,11/03,11:11,122,352,233
7,1997/11/04,06:00,11/05,04:30,14000,100,S14W33,8100,X2.1,11/04,06:10,360,785,Halo
8,1997/11/06,12:20,11/07,08:30,14000,100,S18W63,8100,X9.4,11/06,12:10,360,1556,Halo
9,1997/11/27,13:30,11/27,14:00,14000,7000,N17E63,8113,X2.6,11/27,13:56,91,441,98
10,1997/12/12,22:45,12/12,23:20,14000,8000,N25W52,8116,B9.4,12/13,00:26,73,191,278
11,1998/01/25,15:03,01/25,15:18,14000,10000,N21E25,8141,C1.1,01/25,15:26,360,693,Halo
12,1998/03/29,03:40,03/29,03:52,14000,7000,SW90,nan,nan,03/29,03:48,360,1397,Halo
13,1998/04/20,10:25,04/22,06:00,10000,35,S22W90,8194,M1.4,04/20,10:07,165,1863,284
14,1998/04/23,06:00,04/23,15:30,14000,200,S17E90,8210,X1.2,04/23,05:55,360,1691,Halo
15,1998/04/24,09:17,04/24,09:25,4700,2600,S10E90,8210,C8.9,04/24,08:55,84,1184,100
16,1998/04/27,09:20,04/27,10:00,10000,1000,S16E50,8210,X1.0,04/27,08:56,360,1385,Halo
17,1998/04/29,16:30,04/29,17:00,10000,2000,S18E20,8210,M6.8,04/29,16:58,360,1374,Halo
18,1998/05/02,14:25,05/02,14:50,5000,3000,S15W15,8210,X1.1,05/02,14:06,360,938,Halo
19,1998/05/06,08:25,05/06,08:35,14000,5000,S11W65,8210,X2.7,05/06,08:29,190,1099,309
20,1998/05/09,03:35,05/09,10:00,9000,400,S14W89,8210,M7.7,05/09,03:35,178,2331,262
21,1998/05/11,21:40,05/11,22:00,10000,1000,N32W90,8214,B6.6,05/11,21:55,>301,830,208
22,1998/05/19,10:00,05/19,11:30,14000,3000,N29W46,8222,B7.9,05/19,10:27,139,801,268
23,1998/05/27,13:30,05/27,14:20,4000,1000,N19W62,8226,C7.5,05/27,13:45,268,878,175
24,1998/06/11,10:15,06/11,10:20,8000,4000,N16E86,8243,M1.4,06/11,10:28,177,1223,123
25,1998/06/16,18:20,06/17,21:00,12000,50,S22W90,8232,M1.0,06/16,18:27,281,1484,341
26,1998/06/20,19:39,06/20,20:00,2600,1800,Back,nan,nan,06/20,18:20,360,964,Halo
27,1998/06/22,07:15,06/22,09:20,6000,2000,N16W46,8243,C2.9,06/22,05:01,59,206,265
28,1998/11/02,14:00,11/02,14:40,14000,4000,S25E47,8373,C4.4,11/02,14:18,169,661,116
29,1998/11/05,22:00,11/07,08:00,5000,50,N22W18,8375,M8.4,11/05,20:44,360,1118,Halo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,2000/05/12,23:34,05/12,23:42,14000,7000,E90b,nan,nan,05/12,23:26,360,2604,Halo
71,2000/05/15,16:47,05/16,14:00,4800,40,S24W67,8993,C7.8,05/15,16:26,>165,1212,257
72,2000/06/02,22:00,06/02,22:15,14000,8000,N16E60,9026,M7.6,06/02,21:30,104,547,69
73,2000/06/06,15:20,06/08,09:00,14000,40,N20E18,9026,X2.3,06/06,15:54,360,1119,Halo
74,2000/06/10,17:15,06/10,18:45,10000,1000,N22W38,9026,M5.2,06/10,17:08,360,1108,Halo
75,2000/06/15,19:52,06/15,19:56,5000,2500,N20W65,9041,M1.8,06/15,20:06,116,1081,298
76,2000/06/17,03:00,06/17,04:15,14000,1000,N22W72,9041,M3.5,06/17,03:28,133,857,298
77,2000/06/19,01:19,06/19,01:22,3800,1900,N42E60,nan,nan,06/18,21:30,49,459,8
78,2000/06/23,14:40,06/22,15:05,14000,2000,N26W72,9042,M3.0,06/23,14:54,>198,847,282
79,2000/06/25,08:10,06/25,09:00,12000,2500,N16W55,9046,M1.9,06/25,07:54,165,1617,262
80,2000/07/10,22:00,07/10,23:30,14000,1000,N18E49,9077,M5.7,07/10,21:50,>289,1352,67
81,2000/07/11,13:00,07/11,13:30,12000,1000,N18E27,9077,X1.0,07/11,13:27,360,1078,Halo
82,2000/07/12,20:05,07/12,20:35,6000,1000,N19W61,9070,M1.5,07/12,20:30,101,820,281
83,2000/07/14,10:30,07/15,14:30,14000,80,N22W07,9077,X5.7,07/14,10:54,360,1674,Halo
84,2000/07/22,11:45,07/22,12:45,14000,2000,N14W56,9085,M3.7,07/22,11:54,>229,1230,259
85,2000/08/11,11:35,08/11,11:59,2800,2000,NW90b,nan,nan,08/11,07:31,70,1071,273
86,2000/09/12,12:00,09/13,12:20,14000,60,S19W06,DSF,M1.0,09/12,11:54,360,1550,Halo
87,2000/09/12,18:15,09/12,19:00,2000,1000,NE90b,nan,nan,09/12,17:30,360,1053,Halo
88,2000/09/16,04:30,09/16,10:30,14000,400,N14W07,9165,M5.9,09/16,05:18,360,1215,Halo
89,2000/09/19,08:45,09/19,10:20,12000,1500,N14W46,9165,M5.1,09/19,08:50,76,766,283
90,2000/09/25,02:20,09/25,03:00,14000,1000,N09W18,9169,M1.8,09/25,02:50,360,587,Halo
91,2000/10/05,22:10,10/05,22:35,5000,1250,N25W90,9177,nan,10/05,18:26,86,1046,323
92,2000/10/16,07:10,10/16,08:00,14000,1000,N03W90,9182,M2.5,10/16,07:27,360,1336,Halo
93,2000/10/25,09:30,10/25,24:00,10000,300,N09W63,9199,C4.0,10/25,08:26,360,770,Halo
94,2000/11/03,18:35,11/03,18:45,4000,2500,N02W02,9213,C3.2,11/03,18:26,360,291,Halo
95,2000/11/08,23:20,11/09,12:00,4000,200,N10W77,9213,M7.4,11/08,23:06,>170,1738,271
96,2000/11/09,16:15,11/11,04:00,10000,40,S11E10,9221,M1.0,nan,nan,nan,nan,nan
97,2000/11/12,14:25,11/12,14:40,3000,2000,S14E05,9227,C4.4,11/12,14:50,50,581,257
98,2000/11/23,08:16,11/23,08:35,14000,9000,S26W40,9238,C5.4,11/23,06:06,360,492,Halo
99,2000/11/23,21:00,11/23,21:06,3500,3000,S20E60,9239,C7.9,11/23,21:30,148,1198,124

# Halo

In [32]:
# new column to indicate halo
new_df['is_halo'] = new_df['CPA'].eq('Halo')


# replace halo with na
new_df.loc[new_df['CPA'].str.contains('Halo'), 'CPA'] = 'na'

In [33]:
new_df[:100]

,startDate,startTime,endDate,endTime,startFrequency,endFrequency,flare_Location,flare_region,importance,CME_Date,CME_Time,width,speed,CPA,is_halo
0,1997/04/01,14:00,04/01,14:15,8000,4000,S25E16,8026,M1.3,04/01,15:18,79,312,74,False
1,1997/04/07,14:30,04/07,17:30,11000,1000,S28E19,8027,C6.8,04/07,14:27,360,878,na,True
2,1997/05/12,05:15,05/14,16:00,12000,80,N21W08,8038,C1.3,05/12,05:30,360,464,na,True
3,1997/05/21,20:20,05/21,22:00,5000,500,N05W12,8040,M1.3,05/21,21:00,165,296,263,False
4,1997/09/23,21:53,09/23,22:16,6000,2000,S29E25,8088,C1.4,09/23,22:02,155,712,133,False
5,1997/11/03,05:15,11/03,12:00,14000,250,S20W13,8100,C8.6,11/03,05:28,109,227,240,False
6,1997/11/03,10:30,11/03,11:30,14000,5000,S16W21,8100,M4.2,11/03,11:11,122,352,233,False
7,1997/11/04,06:00,11/05,04:30,14000,100,S14W33,8100,X2.1,11/04,06:10,360,785,na,True
8,1997/11/06,12:20,11/07,08:30,14000,100,S18W63,8100,X9.4,11/06,12:10,360,1556,na,True
9,1997/11/27,13:30,11/27,14:00,14000,7000,N17E63,8113,X2.6,11/27,13:56,91,441,98,False
10,1997/12/12,22:45,12/12,23:20,14000,8000,N25W52,8116,B9.4,12/13,00:26,73,191,278,False
11,1998/01/25,15:03,01/25,15:18,14000,10000,N21E25,8141,C1.1,01/25,15:26,360,693,na,True
12,1998/03/29,03:40,03/29,03:52,14000,7000,SW90,nan,nan,03/29,03:48,360,1397,na,True
13,1998/04/20,10:25,04/22,06:00,10000,35,S22W90,8194,M1.4,04/20,10:07,165,1863,284,False
14,1998/04/23,06:00,04/23,15:30,14000,200,S17E90,8210,X1.2,04/23,05:55,360,1691,na,True
15,1998/04/24,09:17,04/24,09:25,4700,2600,S10E90,8210,C8.9,04/24,08:55,84,1184,100,False
16,1998/04/27,09:20,04/27,10:00,10000,1000,S16E50,8210,X1.0,04/27,08:56,360,1385,na,True
17,1998/04/29,16:30,04/29,17:00,10000,2000,S18E20,8210,M6.8,04/29,16:58,360,1374,na,True
18,1998/05/02,14:25,05/02,14:50,5000,3000,S15W15,8210,X1.1,05/02,14:06,360,938,na,True
19,1998/05/06,08:25,05/06,08:35,14000,5000,S11W65,8210,X2.7,05/06,08:29,190,1099,309,False
20,1998/05/09,03:35,05/09,10:00,9000,400,S14W89,8210,M7.7,05/09,03:35,178,2331,262,False
21,1998/05/11,21:40,05/11,22:00,10000,1000,N32W90,8214,B6.6,05/11,21:55,>301,830,208,False
22,1998/05/19,10:00,05/19,11:30,14000,3000,N29W46,8222,B7.9,05/19,10:27,139,801,268,False
23,1998/05/27,13:30,05/27,14:20,4000,1000,N19W62,8226,C7.5,05/27,13:45,268,878,175,False
24,1998/06/11,10:15,06/11,10:20,8000,4000,N16E86,8243,M1.4,06/11,10:28,177,1223,123,False
25,1998/06/16,18:20,06/17,21:00,12000,50,S22W90,8232,M1.0,06/16,18:27,281,1484,341,False
26,1998/06/20,19:39,06/20,20:00,2600,1800,Back,nan,nan,06/20,18:20,360,964,na,True
27,1998/06/22,07:15,06/22,09:20,6000,2000,N16W46,8243,C2.9,06/22,05:01,59,206,265,False
28,1998/11/02,14:00,11/02,14:40,14000,4000,S25E47,8373,C4.4,11/02,14:18,169,661,116,False
29,1998/11/05,22:00,11/07,08:00,5000,50,N22W18,8375,M8.4,11/05,20:44,360,1118,na,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,2000/05/12,23:34,05/12,23:42,14000,7000,E90b,nan,nan,05/12,23:26,360,2604,na,True
71,2000/05/15,16:47,05/16,14:00,4800,40,S24W67,8993,C7.8,05/15,16:26,>165,1212,257,False
72,2000/06/02,22:00,06/02,22:15,14000,8000,N16E60,9026,M7.6,06/02,21:30,104,547,69,False
73,2000/06/06,15:20,06/08,09:00,14000,40,N20E18,9026,X2.3,06/06,15:54,360,1119,na,True
74,2000/06/10,17:15,06/10,18:45,10000,1000,N22W38,9026,M5.2,06/10,17:08,360,1108,na,True
75,2000/06/15,19:52,06/15,19:56,5000,2500,N20W65,9041,M1.8,06/15,20:06,116,1081,298,False
76,2000/06/17,03:00,06/17,04:15,14000,1000,N22W72,9041,M3.5,06/17,03:28,133,857,298,False
77,2000/06/19,01:19,06/19,01:22,3800,1900,N42E60,nan,nan,06/18,21:30,49,459,8,False
78,2000/06/23,14:40,06/22,15:05,14000,2000,N26W72,9042,M3.0,06/23,14:54,>198,847,282,False
79,2000/06/25,08:10,06/25,09:00,12000,2500,N16W55,9046,M1.9,06/25,07:54,165,1617,262,False
80,2000/07/10,22:00,07/10,23:30,14000,1000,N18E49,9077,M5.7,07/10,21:50,>289,1352,67,False
81,2000/07/11,13:00,07/11,13:30,12000,1000,N18E27,9077,X1.0,07/11,13:27,360,1078,na,True
82,2000/07/12,20:05,07/12,20:35,6000,1000,N19W61,9070,M1.5,07/12,20:30,101,820,281,False
83,2000/07/14,10:30,07/15,14:30,14000,80,N22W07,9077,X5.7,07/14,10:54,360,1674,na,True
84,2000/07/22,11:45,07/22,12:45,14000,2000,N14W56,9085,M3.7,07/22,11:54,>229,1230,259,False
85,2000/08/11,11:35,08/11,11:59,2800,2000,NW90b,nan,nan,08/11,07:31,70,1071,273,False
86,2000/09/12,12:00,09/13,12:20,14000,60,S19W06,DSF,M1.0,09/12,11:54,360,1550,na,True
87,2000/09/12,18:15,09/12,19:00,2000,1000,NE90b,nan,nan,09/12,17:30,360,1053,na,True
88,2000/09/16,04:30,09/16,10:30,14000,400,N14W07,9165,M5.9,09/16,05:18,360,1215,na,True
89,2000/09/19,08:45,09/19,10:20,12000,1500,N14W46,9165,M5.1,09/19,08:50,76,766,283,False
90,2000/09/25,02:20,09/25,03:00,14000,1000,N09W18,9169,M1.8,09/25,02:50,360,587,na,True
91,2000/10/05,22:10,10/05,22:35,5000,1250,N25W90,9177,nan,10/05,18:26,86,1046,323,False
92,2000/10/16,07:10,10/16,08:00,14000,1000,N03W90,9182,M2.5,10/16,07:27,360,1336,na,True
93,2000/10/25,09:30,10/25,24:00,10000,300,N09W63,9199,C4.0,10/25,08:26,360,770,na,True
94,2000/11/03,18:35,11/03,18:45,4000,2500,N02W02,9213,C3.2,11/03,18:26,360,291,na,True
95,2000/11/08,23:20,11/09,12:00,4000,200,N10W77,9213,M7.4,11/08,23:06,>170,1738,271,False
96,2000/11/09,16:15,11/11,04:00,10000,40,S11E10,9221,M1.0,nan,nan,nan,nan,nan,False
97,2000/11/12,14:25,11/12,14:40,3000,2000,S14E05,9227,C4.4,11/12,14:50,50,581,257,False
98,2000/11/23,08:16,11/23,08:35,14000,9000,S26W40,9238,C5.4,11/23,06:06,360,492,na,True
99,2000/11/23,21:00,11/23,21:06,3500,3000,S20E60,9239,C7.9,11/23,21:30,148,1198,124,False

In [34]:
new_df.width.str.contains('>')

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21      True
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...
452    False
453    False
454    False
455    False
456    False
457    False
458    False
459    False
460    False
461    False
462    False
463    False
464    False
465    False
466    False
467    False
468    False
469    False
470    False
471    False
472    False
473    False
474     True
475    False
476    False
477    False
478    False
479    False
480    False
481    False
Name: width, Length: 482, dtype: bool

In [35]:
# Lower bound column
new_df['lower_bound'] = new_df.width.str.contains('>')

In [36]:
# remove non-numberic characters
new_df.loc[new_df.width.str.contains('>'), 'width'] = new_df.loc[new_df.width.str.contains('>'), 'width'].replace(r'>', '', regex=True)

In [37]:
new_df.width

0        79
1       360
2       360
3       165
4       155
5       109
6       122
7       360
8       360
9        91
10       73
11      360
12      360
13      165
14      360
15       84
16      360
17      360
18      360
19      190
20      178
21      301
22      139
23      268
24      177
25      281
26      360
27       59
28      169
29      360
       ...
452      96
453     360
454     360
455     360
456     360
457     360
458     360
459     186
460     254
461    360h
462     360
463     360
464     177
465     360
466     360
467     360
468     360
469      87
470     252
471     134
472     360
473     159
474     210
475     142
476     141
477     360
478     108
479     360
480     360
481     360
Name: width, Length: 482, dtype: object

In [38]:
new_df[:30]

,startDate,startTime,endDate,endTime,startFrequency,endFrequency,flare_Location,flare_region,importance,CME_Date,CME_Time,width,speed,CPA,is_halo,lower_bound
0,1997/04/01,14:00,04/01,14:15,8000,4000,S25E16,8026,M1.3,04/01,15:18,79,312,74,False,False
1,1997/04/07,14:30,04/07,17:30,11000,1000,S28E19,8027,C6.8,04/07,14:27,360,878,na,True,False
2,1997/05/12,05:15,05/14,16:00,12000,80,N21W08,8038,C1.3,05/12,05:30,360,464,na,True,False
3,1997/05/21,20:20,05/21,22:00,5000,500,N05W12,8040,M1.3,05/21,21:00,165,296,263,False,False
4,1997/09/23,21:53,09/23,22:16,6000,2000,S29E25,8088,C1.4,09/23,22:02,155,712,133,False,False
5,1997/11/03,05:15,11/03,12:00,14000,250,S20W13,8100,C8.6,11/03,05:28,109,227,240,False,False
6,1997/11/03,10:30,11/03,11:30,14000,5000,S16W21,8100,M4.2,11/03,11:11,122,352,233,False,False
7,1997/11/04,06:00,11/05,04:30,14000,100,S14W33,8100,X2.1,11/04,06:10,360,785,na,True,False
8,1997/11/06,12:20,11/07,08:30,14000,100,S18W63,8100,X9.4,11/06,12:10,360,1556,na,True,False
9,1997/11/27,13:30,11/27,14:00,14000,7000,N17E63,8113,X2.6,11/27,13:56,91,441,98,False,False
10,1997/12/12,22:45,12/12,23:20,14000,8000,N25W52,8116,B9.4,12/13,00:26,73,191,278,False,False
11,1998/01/25,15:03,01/25,15:18,14000,10000,N21E25,8141,C1.1,01/25,15:26,360,693,na,True,False
12,1998/03/29,03:40,03/29,03:52,14000,7000,SW90,nan,nan,03/29,03:48,360,1397,na,True,False
13,1998/04/20,10:25,04/22,06:00,10000,35,S22W90,8194,M1.4,04/20,10:07,165,1863,284,False,False
14,1998/04/23,06:00,04/23,15:30,14000,200,S17E90,8210,X1.2,04/23,05:55,360,1691,na,True,False
15,1998/04/24,09:17,04/24,09:25,4700,2600,S10E90,8210,C8.9,04/24,08:55,84,1184,100,False,False
16,1998/04/27,09:20,04/27,10:00,10000,1000,S16E50,8210,X1.0,04/27,08:56,360,1385,na,True,False
17,1998/04/29,16:30,04/29,17:00,10000,2000,S18E20,8210,M6.8,04/29,16:58,360,1374,na,True,False
18,1998/05/02,14:25,05/02,14:50,5000,3000,S15W15,8210,X1.1,05/02,14:06,360,938,na,True,False
19,1998/05/06,08:25,05/06,08:35,14000,5000,S11W65,8210,X2.7,05/06,08:29,190,1099,309,False,False
20,1998/05/09,03:35,05/09,10:00,9000,400,S14W89,8210,M7.7,05/09,03:35,178,2331,262,False,False
21,1998/05/11,21:40,05/11,22:00,10000,1000,N32W90,8214,B6.6,05/11,21:55,301,830,208,False,True
22,1998/05/19,10:00,05/19,11:30,14000,3000,N29W46,8222,B7.9,05/19,10:27,139,801,268,False,False
23,1998/05/27,13:30,05/27,14:20,4000,1000,N19W62,8226,C7.5,05/27,13:45,268,878,175,False,False
24,1998/06/11,10:15,06/11,10:20,8000,4000,N16E86,8243,M1.4,06/11,10:28,177,1223,123,False,False
25,1998/06/16,18:20,06/17,21:00,12000,50,S22W90,8232,M1.0,06/16,18:27,281,1484,341,False,False
26,1998/06/20,19:39,06/20,20:00,2600,1800,Back,nan,nan,06/20,18:20,360,964,na,True,False
27,1998/06/22,07:15,06/22,09:20,6000,2000,N16W46,8243,C2.9,06/22,05:01,59,206,265,False,False
28,1998/11/02,14:00,11/02,14:40,14000,4000,S25E47,8373,C4.4,11/02,14:18,169,661,116,False,False
29,1998/11/05,22:00,11/07,08:00,5000,50,N22W18,8375,M8.4,11/05,20:44,360,1118,na,True,False

# DateTime

In [39]:
new_df.columns

Index(['startDate', 'startTime', 'endDate', 'endTime', 'startFrequency',
       'endFrequency', 'flare_Location', 'flare_region', 'importance',
       'CME_Date', 'CME_Time', 'width', 'speed', 'CPA', 'is_halo',
       'lower_bound'],
      dtype='object')

In [40]:
# Testing 
new_df.startDate.str.contains('nan').sum(), new_df.endDate.str.contains('nan').sum()

(0, 0)

In [41]:
new_df['endDate'] = new_df['startDate'].str.slice(start=0, stop=5) + new_df['endDate'] + ' ' + new_df['endTime']
new_df['startDate'] = new_df['startDate'] + ' ' + new_df['startTime']

# drop
new_df.drop(['endTime', 'startTime'], axis=1, inplace=True)

# rename
new_df.rename(columns={'startDate': 'Start_Datetime', 'endDate':'End_Datetime'}, inplace=True)

In [42]:
new_df.Start_Datetime.str.contains('nan').sum(), new_df.End_Datetime.str.contains('nan').sum()

(0, 0)

In [43]:
new_df.columns

Index(['Start_Datetime', 'End_Datetime', 'startFrequency', 'endFrequency',
       'flare_Location', 'flare_region', 'importance', 'CME_Date', 'CME_Time',
       'width', 'speed', 'CPA', 'is_halo', 'lower_bound'],
      dtype='object')

In [44]:
new_df.dtypes

Start_Datetime    object
End_Datetime      object
startFrequency    object
endFrequency      object
flare_Location    object
flare_region      object
importance        object
CME_Date          object
CME_Time          object
width             object
speed             object
CPA               object
is_halo             bool
lower_bound         bool
dtype: object

In [45]:
def custom_to_datetime(date):
    # If the time is 24, set it to 0 and increment day by 1
    if date[11:13] == '24':
        return pd.to_datetime(date[:-5]) + pd.Timedelta(days=1)
    else:
        return pd.to_datetime(date)

In [46]:
for col in ['Start_Datetime', 'End_Datetime']:
    new_df[col] = new_df[col].apply(custom_to_datetime)

In [47]:
new_df.dtypes

Start_Datetime    datetime64[ns]
End_Datetime      datetime64[ns]
startFrequency            object
endFrequency              object
flare_Location            object
flare_region              object
importance                object
CME_Date                  object
CME_Time                  object
width                     object
speed                     object
CPA                       object
is_halo                     bool
lower_bound                 bool
dtype: object

In [48]:
new_df.head()

,Start_Datetime,End_Datetime,startFrequency,endFrequency,flare_Location,flare_region,importance,CME_Date,CME_Time,width,speed,CPA,is_halo,lower_bound
0,1997-04-01 14:00:00,1997-04-01 14:15:00,8000,4000,S25E16,8026,M1.3,04/01,15:18,79,312,74,False,False
1,1997-04-07 14:30:00,1997-04-07 17:30:00,11000,1000,S28E19,8027,C6.8,04/07,14:27,360,878,na,True,False
2,1997-05-12 05:15:00,1997-05-14 16:00:00,12000,80,N21W08,8038,C1.3,05/12,05:30,360,464,na,True,False
3,1997-05-21 20:20:00,1997-05-21 22:00:00,5000,500,N05W12,8040,M1.3,05/21,21:00,165,296,263,False,False
4,1997-09-23 21:53:00,1997-09-23 22:16:00,6000,2000,S29E25,8088,C1.4,09/23,22:02,155,712,133,False,False

In [49]:
new_df.to_csv('nasa.csv')

In [50]:
new_df.tail()

,Start_Datetime,End_Datetime,startFrequency,endFrequency,flare_Location,flare_region,importance,CME_Date,CME_Time,width,speed,CPA,is_halo,lower_bound
477,2014-12-13 14:27:00,2014-12-13 14:51:00,14000,3900,W90b,nan,nan,12/13,14:24,360,2222,na,True,False
478,2014-12-17 04:09:00,2014-12-17 04:19:00,2900,2100,S11E33,12241,M1.1,12/17,02:00,108,869,107,False,False
479,2014-12-17 05:00:00,2014-12-17 05:09:00,14000,11500,S20E09,12242,M8.7,12/17,05:00,360,587,na,True,False
480,2014-12-18 22:31:00,2014-12-18 22:54:00,5100,1300,S11E15,12241,M6.9,12/19,01:04,360,1195,na,True,False
481,2014-12-21 12:05:00,2014-12-21 12:28:00,14000,7400,S14W25,12241,M1.0,12/21,12:12,360,669,na,True,False